services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - PORT=3000
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`cv.vidalotvdt.fr`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  app-network:
    driver: bridge
  coolify:
    external: true
